saveIntervalSeconds: 60 * 15
topListUpdateIntervalSeconds: 10
maxTopListSize: 500
topListCommandsPageSize: 10
incrementIntervalTicks: 10
calendarBucketKeyUpdateIntervalSeconds: 5
timeZoneId: 'Europe/Berlin'
placeholders:
  timeFormat: '<duration [value]="time / 20.0 * 1000.0" units="hd" zeroes="h" />'
  calendarDay: '{lut.day_now}'
  calendarWeek: '{lut.week_now}'
  calendarMonth: '{lut.month_now}'
  calendarYear: '{lut.year_now}'
ranks:
commands:
  playTop:
    name: playtop
  afkTop:
    name: afktop
  playtime:
    name: playtime
    consoleExecutionWithoutName: '{lut.prefix} <&c>Bei Ausführung in der Konsole ist ein Spielername verpflichtend!'
    commandUsage: '{lut.prefix} <&c>Benutzung: /{label} [Spieler]'
    playtimeOfSelf: |
      {lut.prefix} <&7>Du hast <&6><$lut.time_format [time]="play_time" /> <&7>aktiv gespielt und warst <&6><$lut.time_format [time]="afk_time" /> <&7>AFK.
    playtimeOfOther: |
      {lut.prefix} <&e>{player_name} <&7>hat <&6><$lut.time_format [time]="play_time" /> <&7>aktiv gespielt und war <&6><$lut.time_format [time]="afk_time" /> <&7>AFK.
  rewards:
    name: rewards
  main:
    name: playtimerewards
    commandUsage: '{lut.prefix} <&c>Benutzung: /{label} \<<&4 *for-action="actions" *for-separator={,<space/>}>{action}</>>'
    reloadedSuccessfully: '{lut.prefix} <&7>Die Konfiguration wurde erfolgreich <&a>neu geladen<&7>.'
    errorWhileReloading: '{lut.prefix} <&c>Es trat ein Fehler auf, während die Konfiguration neu geladen wurde; siehe Konsole!'
    timeModificationUsage: '{lut.prefix} <&c>Benutzung: /{label} {action} \<Name> \<Dauer>'
    unsupportedDurationUnit: '{lut.prefix} <&c>Unbekannte Einheit <&4>{error_token}</>; wähle aus: <&4 *for-unit="supported_units" *for-separator={,<space/>}>{unit}</>!'
    malformedDurationNumber: '{lut.prefix} <&c>Ungültige Zahl: <&4>{error_token}</>!'
    negativeDurationNumber: '{lut.prefix} <&c>Negative Zahl: <&4>{error_token}</>!'
    zeroDuration: '{lut.prefix} <&c>Die Gesamtdauer muss größer als Null sein!'
    timeModifiedSuccessfully: |
      {lut.prefix} <&7>Die <&6>{time_type} <&7>von <&6><$lut.time_format [time]="delta_time" />
      <&7> wurde dem Spieler <&6>{player_name} <&7>erfolgreich<space/>
      <&a *if="did_add">hinzugefügt</>
      <&c *else>abgezogen</>
      ; alter Stand: <&6><$lut.time_format [time]="prior_value" /></>
      ; neuer Stand: <&6><$lut.time_format [time]="new_value" />.
    exportUsage: |
      {lut.prefix} <&c>Benutzung: /{label} {action}
      <space/>\<<&4 *for-time_type="time_types" *for-separator={,<space/>}>{time_type}</>>
      <space/>\<<&4 *for-top_type="top_types" *for-separator={,<space/>}>{top_type}</>>
      <space/>\<<&4 *for-direction="directions" *for-separator={,<space/>}>{direction}</>>
    exportTimeFormat:
      <duration [value]="time / 20.0 * 1000.0" units="mhd" [zeroes]="time < 20 * 60 then 'm'" />
    exportWriteError: '{lut.prefix} <&c>Beim schreiben der Datei trat ein Fehler auf; siehe Konsole!'
    exportSuccess: '{lut.prefix} <&7>Der Export wurde unter <&a>{file_path}</> abgelegt.'
commonMessages:
  onlyAvailableToPlayers: '{lut.prefix} <&c>Dieser Befehl ist nur für Spieler verfügbar!'
  hasNotPlayedBefore: '{lut.prefix} <&c>Der Spieler <&4>{name} <&c>hat noch nicht zuvor gespielt!'
  topCommandUsage: '{lut.prefix} <&c>Benutzung: /{label} [Seite] [<container *for-type="types" [type] *for-separator={,<space/>} />] [<container *for-direction="directions" [direction] *for-separator={,<space/>} />]'
  topCommandInvalidPage: '{lut.prefix} <&c>Ungültige Seitenzahl: <&4>{input}<&c>!'
  topCommandEmptyTopList: '{lut.prefix} <&c>Die Topliste hat noch keine Einträge!'
  topCommandExceededPages: '{lut.prefix} <&c>Die Seitenzahl <&4>{page} <&c>überschreitet die Gesamtanzahl von <&4>{number_of_pages} Seiten<&c>!'
  topScreen: |
    <&8><&m>{' ' ** 20}</> <&6>Top {time_type}<&8> <&8><&m>{' ' ** 20}</><br/>
    <&7>{top_type}, {top_direction}, Seite {current_page}/{number_of_pages}<br/>
    <br/>
    <container *for-entry="entries" *for-separator={<br/>}>
      <&7>#{entry.place} <&e>{entry.name} <&6><$lut.time_format [time]="entry.time" />
    </container>
    <br/>
topListTypeDisplayNames:
  TOTAL: 'Gesamt'
  DAY: 'Tag'
  WEEK: 'Woche'
  MONTH: 'Monat'
  YEAR: 'Jahr'
timeTypeDisplayNames:
  AFK_TIME: 'AFK-Zeit'
  PLAY_TIME: 'Spielzeit'
topListDirectionDisplayNames:
  ASCENDING: 'Aufsteigend'
  DESCENDING: 'Absteigend'
rewardsDisplay:
  title: '<&8>{player_name}''s Belohnungen'
  rows: 5
  items:
    statistics:
      type: OAK_HANGING_SIGN
      slots: 13
      name: |
        <reset>
          <&8>» <&6>Statistiken <&8>«
      lore: |
        <reset>
          <br/>
          <&9>Gesamtzeit<br/>
          <&8>➥ <&e>Aktiv <&6><$lut.time_format [time]="play_time" /> <&7>(#{play_time_total_descending_top_place})<br/>
          <&8>➥ <&e>AFK <&6><$lut.time_format [time]="afk_time" /> <&7>(#{afk_time_total_descending_top_place})<br/>
          <br/>
          <&9>Dieser Tag <&7>({lut.day_now})<br/>
          <&8>➥ <&e>Aktiv <&6><$lut.time_format [time]="play_time_day" /> <&7>(#{play_time_day_descending_top_place})<br/>
          <&8>➥ <&e>AFK <&6><$lut.time_format [time]="afk_time_day" /> <&7>(#{afk_time_day_descending_top_place})<br/>
          <br/>
          <&9>Diese Woche <&7>({lut.week_now})<br/>
          <&8>➥ <&e>Aktiv <&6><$lut.time_format [time]="play_time_week" /> <&7>(#{play_time_week_descending_top_place})<br/>
          <&8>➥ <&e>AFK <&6><$lut.time_format [time]="afk_time_week" /> <&7>(#{afk_time_week_descending_top_place})<br/>
          <br/>
          <&9>Diesen Monat <&7>({lut.month_now})<br/>
          <&8>➥ <&e>Aktiv <&6><$lut.time_format [time]="play_time_month" /> <&7>(#{play_time_month_descending_top_place})<br/>
          <&8>➥ <&e>AFK <&6><$lut.time_format [time]="afk_time_month" /> <&7>(#{afk_time_month_descending_top_place})<br/>
          <br/>
          <&9>Dieses Jahr <&7>({lut.year_now})<br/>
          <&8>➥ <&e>Aktiv <&6><$lut.time_format [time]="play_time_year" /> <&7>(#{play_time_year_descending_top_place})<br/>
          <&8>➥ <&e>AFK <&6><$lut.time_format [time]="afk_time_year" /> <&7>(#{afk_time_year_descending_top_place})<br/>
    filler:
      type: BLACK_STAINED_GLASS_PANE
      name: ' '
      slots: '(0..last_slot) - (28..34)'

sLut:
cLut:
  prefix: '<&7>[<&6>Spielzeit<&7>]'
  time_format: |
    <duration [value]="time / 20.0 * 1000.0" units="smhd" [zeroes]="time < 20 then 's'" />
  date_now: '<date [format] locale="de" />'
  day_now: '<$lut.date_now format="EEE" />'
  week_now: '<$lut.date_now format="YYYY-''W''ww" />'
  month_now: '<$lut.date_now format="MMM" />'
  year_now: '<$lut.date_now format="yyyy" />'