# This is a partial config, containing only the difference between the default-setup and ours.

ranks:
  siedler:
    requiredPlayTime: 1d
    notification:
      self:
        title: '{lut.rank_prefix.siedler}'
        subtitle: '<&6>Rang erhalten!'
      broadcast:
        chat: '<$lut.uprank_broadcast [rank-prefix]="lut.rank_prefix.siedler" />'
    icon:
      slot: 28
      pending:
        type: STONE_BRICKS
        name: '<reset><&8>» {lut.rank_prefix.siedler} <&8>«'
        lore: '<reset><$lut.rank_description.siedler pending>'
      claimed:
        type: STONE_BRICKS
        name: '<reset><&8>» {lut.rank_prefix.siedler} <&8>«'
        lore: '<reset><$lut.rank_description.siedler>'
  buerger:
    requiredPlayTime: 12d
    notification:
      self:
        title: '{lut.rank_prefix.buerger}'
        subtitle: '<&6>Rang erhalten!'
      broadcast:
        chat: '<$lut.uprank_broadcast [rank-prefix]="lut.rank_prefix.buerger" />'
    icon:
      slot: 29
      pending:
        type: BEACON
        name: '<reset><&8>» {lut.rank_prefix.buerger} <&8>«'
        lore: '<reset><$lut.rank_description.buerger pending>'
      claimed:
        type: BEACON
        name: '<reset><&8>» {lut.rank_prefix.buerger} <&8>«'
        lore: '<reset><$lut.rank_description.buerger>'
  aristokrat:
    requiredPlayTime: 25d
    notification:
      self:
        title: '{lut.rank_prefix.aristokrat}'
        subtitle: '<&6>Rang erhalten!'
      broadcast:
        chat: '<$lut.uprank_broadcast [rank-prefix]="lut.rank_prefix.aristokrat" />'
    icon:
      slot: 30
      pending:
        type: GOLD_BLOCK
        name: '<reset><&8>» {lut.rank_prefix.aristokrat} <&8>«'
        lore: '<reset><$lut.rank_description.aristokrat pending>'
      claimed:
        type: GOLD_BLOCK
        name: '<reset><&8>» {lut.rank_prefix.aristokrat} <&8>«'
        lore: '<reset><$lut.rank_description.aristokrat>'
cLut:
  uprank_broadcast: '{lut.prefix} <&7>Der Spieler <&6>{player_name} <&7>hat den {rank_prefix}-Rang nach Erreichen einer Spielzeit von <&6><$lut.time_format [time]="required_time" /> <&7>erhalten!'
  required_time_section: |
    <&d>Benötigte Spielzeit: <&e><$lut.time_format [time]="required_time" />, ohne AFK-Zeit!<br/>
    <br/>
  remaining_time_section: |
    <br/><br/>
    <container *if="has('pending')">
      <&d>Zeit bis zum Aufstieg: <&e><$lut.time_format [time]="remaining_time" />
    </container>
    <container *else>
      <&a>Bereits erhalten!
    </container>
  rank_prefix:
    entdecker: '<gradient c="#C4E90D" c="#08B629">[Entdecker]'
    siedler: '<gradient c="#0ECCFF" c="#006DFD">[Siedler]'
    buerger: '<gradient c="#BE1EFF" c="#09C872">[Bürger]'
    aristokrat: '<gradient c="#CDB305" c="#F1FD0C">[Aristokrat]'
  rank_description:
    siedler: |
      {lut.required_time_section}
      <&a><&l>Vorteile:</><br/>
      <#9BCD9B><&o>Alles, was {lut.rank_prefix.entdecker} auch können, sowie:</&o><br/>
      <#C1FFC1>
        20 Homepunkte<br/>
        2 ImageFrames Bilder<br/>
        Pipes + PipePredicates<br/>
        Painting-Switcher<br/>
        Hidden-Switch<br/>
        Sign-Copier + SignEdit<br/>
        Zugriff aufs Kopfplugin mit <#9370db>/hdb</><br/>
        Lava-Schwämme (nasse Schwämme saugen Lava statt Wasser)<br/>
        MultiBreak (Abbauradius max. 2x2x2)<br/>
        Private virtuelle Truhe mit <#9370db>/pv</> mit 27 Slots<br/>
        Uncraft von Sachen mit <#9370db>/uc</><br/>
        Inventarfilter beim Aufsammeln mit <#9370db>/invfilter</> \<item/variable>
      </#C1FFC1>
      {lut.remaining_time_section}
    buerger: |
      {lut.required_time_section}
      <&a><&l>Vorteile:</><br/>
      <#9BCD9B><&o>Alles, was {lut.rank_prefix.siedler} auch können, sowie:</&o><br/>
      <#C1FFC1>
        50 Homepunkte<br/>
        5 ImageFrames Bilder<br/>
        Teleporter<br/>
        Lift-Schilder<br/>
        Edit-Armorstands (EAS)<br/>
        /nick (Nicknamen setzen)<br/>
        /anvil (Mobiler Amboss)<br/>
        Item-Name auf das in der Hand gehaltene mit <#9370db>/itemname \<name></><br/>
        MultiBreak (Abbauradius max. 3x3x3)<br/>
        Private virtuelle Truhe mit <#9370db>/pv</> mit 36 Slots<br/>
        Spielerzeit einstellbar mit <#9370db>/ptime \<Zeit></> in der Bauwelt<br/>
        Uncraft von allem mit <#9370db>/uc -a</>
      </#C1FFC1>
      {lut.remaining_time_section}
    aristokrat: |
      {lut.required_time_section}
      <&a><&l>Vorteile:</><br/>
      <#9BCD9B><&o>Alles, was {lut.rank_prefix.buerger} auch können, sowie:</&o><br/>
      <#C1FFC1>
        100 Homepunkte<br/>
        7 ImageFrames Bilder<br/>
        Auto-Planter<br/>
        Auto-Crafter<br/>
        Transmitter/Receiver<br/>
        MultiBreak (Abbauradius max. 4x4x4)<br/>
        Private virtuelle Truhe mit <#9370db>/pv</> mit 45 Slots
      </#C1FFC1>
      {lut.remaining_time_section}